---
apiVersion: v1
kind: Namespace
metadata:
  name: miztiik-automation-ns
  labels:
    app: shopfront
    role: webfront
    project: emr-on-eks
    owner: miztiik-automation
    compute_provider: on_demand
    dept: engineering
    team: red-shirts
  annotations:
    contact: github.com/miztiik
